import Head from "next/head";
import React from "react";
import { DragSortingUpload } from "../components/file_upload";

export default function Upload_Page() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DragSortingUpload />
    </div>
  );
}
